/**
 * UniTime API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ActivityDto {
    startTime?: string;

    endTime?: string;

    isAllDay?: boolean;

    privacy?: ActivityDto.PrivacyEnum;

    images?: Array<models.FileDto>;

    participants?: Array<models.UserListDto>;

    name?: string;

    descriptions?: Array<models.DescriptionDto>;

    location?: models.LocationDto;

    ratings?: Array<models.RatingDto>;

    comments?: Array<models.CommentDto>;

    tags?: Array<models.TagDto>;

    bookmarkingUsers?: Array<models.BookmarkingUserListDto>;

    owner?: models.UserListDto;

    id?: string;

}
export namespace ActivityDto {
    export enum PrivacyEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2
    }
}
