/**
 * UniTime API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UpdateActivityInput {
    startTime?: string;

    endTime?: string;

    isAllDay?: boolean;

    alertTimings?: Array<UpdateActivityInput.AlertTimingsEnum>;

    privacy?: UpdateActivityInput.PrivacyEnum;

    previewToken?: string;

    name: string;

    descriptionIds?: Array<number>;

    tagTexts?: Array<string>;

    locationId?: string;

    id?: string;

}
export namespace UpdateActivityInput {
    export enum AlertTimingsEnum {
        _0 = <any> '0',
        _1 = <any> '1',
        _2 = <any> '2',
        _3 = <any> '3',
        _4 = <any> '4',
        _5 = <any> '5',
        _6 = <any> '6',
        _7 = <any> '7',
        _8 = <any> '8'
    }
    export enum PrivacyEnum {
        NUMBER_0 = <any> 0,
        NUMBER_10 = <any> 10,
        NUMBER_20 = <any> 20,
        NUMBER_30 = <any> 30
    }
}
